### ISSUE TITLE
Error when running the code

### ISSUE THREAD

**Issue by MangledPotat0** [zkdavis/steal_the_micro_cosmos#1]
michael@michael-XPS-15-9500:~/steal_the_micro_cosmos$ python main.py 
  File "main.py", line 9
    def start(driver:webdriver):
                    ^
SyntaxError: invalid syntax

**Comment by MangledPotat0** [comment]
(base) michael@michael-XPS-15-9500:~/steal_the_micro_cosmos$ python main.py
Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/home/michael/anaconda3/lib/python3.9/subprocess.py", line 951, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/michael/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/michael/steal_the_micro_cosmos/drivers/linux/geckodriver')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/steal_the_micro_cosmos/main.py", line 49, in <module>
    driver = get_driver()
  File "/home/michael/steal_the_micro_cosmos/main.py", line 35, in get_driver
    driver = webdriver.Firefox(executable_path=seleniumlocations)
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in init
    self.service.start()
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by MichaelVennettilli** [comment]
Traceback (most recent call last):
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/home/michael/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/michael/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/home/michael/steal_the_micro_cosmos/drivers/linux/geckodriver')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/steal_the_micro_cosmos/main.py", line 49, in <module>
    driver = get_driver()
  File "/home/michael/steal_the_micro_cosmos/main.py", line 35, in get_driver
    driver = webdriver.Firefox(executable_path=seleniumlocations)
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/home/michael/anaconda3/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions.

**Comment by MichaelVennettilli** [comment]
Images aren't being downloaded to the proper directory.

**Comment by MangledPotat0** [comment]
> Images aren't being downloaded to the proper directory.

I moved it to a new issue since this is a separate problem.
